"""Add bonus features tables

Revision ID: ab180a3f8c14
Revises: 
Create Date: 2025-12-14 16:28:43.696487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab180a3f8c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalized_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True),
    sa.Column('personalized_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'difficulty_level', name='uix_chapter_difficulty')
    )
    op.create_index(op.f('ix_personalized_content_chapter_id'), 'personalized_content', ['chapter_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'language_code', name='uix_chapter_language')
    )
    op.create_index(op.f('ix_translations_chapter_id'), 'translations', ['chapter_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_background', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='softwarebackground'), nullable=False),
    sa.Column('hardware_background', sa.Enum('NONE', 'BASIC', 'HANDS_ON', name='hardwarebackground'), nullable=False),
    sa.Column('python_familiar', sa.Boolean(), nullable=False),
    sa.Column('ros_familiar', sa.Boolean(), nullable=False),
    sa.Column('aiml_familiar', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_translations_chapter_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_personalized_content_chapter_id'), table_name='personalized_content')
    op.drop_table('personalized_content')
    # ### end Alembic commands ###
